version: 1.0.0.{build}
skip_tags: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: TvMaze_build_nuget.bat
artifacts:
- path: packages
  name: TvMaze.Packages.$(APPVEYOR_BUILD_VERSION)
- path: TvMaze.$(APPVEYOR_BUILD_VERSION).nupkg
  name: TvMaze.$(APPVEYOR_BUILD_VERSION).nupkg